spring.application.name=expenses

#FORMAT OF URL:  jdbc:postgresql://<host>:<port>/<dbName>
spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.address=0.0.0.0
#server.severlet.context-path=/api/v1

aes.encryption.secret-key=${AES_SECRET}
jwt.token.secret-key=${JWT_TOKEN_SECRET}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_ID}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.sender.email=${GMAIL_ID}
mail.sender.name=Expense Tracker
